const METALS={gold:{name:'Gold',symbol:'XAU',pure:'Gold'},silver:{name:'Silver',symbol:'XAG',pure:'Silver'},platinum:{name:'Platinum',symbol:'XPT',pure:'Platinum'},palladium:{name:'Palladium',symbol:'XPD',pure:'Palladium'},copper:{name:'Copper',symbol:'XCU',pure:'Copper'}};
const key=new URLSearchParams(location.search).get('metal'); const metal=METALS[key]||METALS.gold; const $=id=>document.getElementById(id); let spot=null, pureBid=null, selectedMode=null;
document.title=`${metal.name} Hedge Calculator`; $('symbol').textContent=metal.symbol; $('title').textContent=`${metal.name} hedge exit calculator`;
const money=n=>n==null||!Number.isFinite(n)?'—':(n<0?'-$':'$')+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=(n,b)=>b?`${n>=0?'+':''}${(n/b*100).toFixed(2)}% vs spot`:'';
function value(id){const n=Number($(id).value);return Number.isFinite(n)?n:null}
function render(){const bid=value('bid'),cost=value('cost'),hedge=value('hedge')||0,fees=value('fees')||0,rewards=value('rewards')||0; $('selected').textContent=money(bid);$('selectedMeta').textContent=bid&&spot?pct(bid-spot,spot):'Pick a price below';document.querySelectorAll('[data-offset]').forEach(b=>{const n=Number(b.dataset.offset),v=spot&&Math.round(spot*(1+n/100)*100)/100;b.querySelector('em').textContent=money(v);b.classList.toggle('on',selectedMode===n)});const physical=bid!=null&&cost!=null?bid-cost:null, net=physical!=null?physical+hedge-fees+rewards:null,be=cost!=null?cost-hedge+fees-rewards:null;$('physical').textContent=money(physical);$('breakeven').textContent=money(be);$('net').textContent=money(net);$('result').className='result'+(net==null?'':net>=0?' good':' bad');$('resultText').textContent=net==null?'Enter your cost basis and a dealer bid.':net>=0?`${money(net)} above break-even.`:`${money(-net)} below break-even.`;localStorage.setItem(`hedge.${key}`,JSON.stringify({cost:$('cost').value,hedge:$('hedge').value,fees:$('fees').value,rewards:$('rewards').value,bid:$('bid').value}));}
function useBid(n,mode=null){if(n==null)return;selectedMode=mode;$('bid').value=n.toFixed(2);render()}
async function spotPrice(){try{let r=await fetch(`api/spot?metal=${encodeURIComponent(metal.pure)}`,{cache:'no-store'});if(!r.ok)throw Error();let d=await r.json();spot=Number(d.price);$('spot').textContent=money(spot);$('spotMeta').textContent=d.source||'live quote'}catch(e){try{let r=await fetch(`https://api.gold-api.com/price/${metal.symbol}`,{cache:'no-store'});let d=await r.json();spot=Number(d.price);$('spot').textContent=money(spot);$('spotMeta').textContent='gold-api.com'}catch(_){$('spot').textContent='Unavailable';$('spotMeta').textContent='Use a manual quote'}}render()}
async function collectPure(){const b=$('collectpure');b.disabled=true;b.querySelector('em').textContent='Loading…';try{let r=await fetch(`api/collectpure/highest-bid?metal=${encodeURIComponent(metal.pure)}`,{cache:'no-store'});let d=await r.json();if(!r.ok||!Number.isFinite(Number(d.price)))throw Error(d.error||'No active bid');pureBid=Number(d.price);$('cpTicker').textContent=money(pureBid);$('cpMeta').textContent=d.product||'current offer';$('cpNotice').textContent=`CollectPure bid: ${money(pureBid)} · ${d.product||'product-specific offer'}. Confirm its unit before using it as a per-ounce price.`;useBid(pureBid,'collectpure')}catch(e){$('cpNotice').textContent='CollectPure bids require the local server with COLLECTPURE_API_KEY configured.'}finally{b.disabled=false;b.querySelector('em').textContent='highest bid'}}
for(const id of ['bid','cost','hedge','fees','rewards'])$(id).addEventListener('input',()=>{selectedMode=null;render()});document.querySelectorAll('[data-offset]').forEach(b=>b.onclick=()=>{let n=Number(b.dataset.offset);if(spot)useBid(Math.round(spot*(1+n/100)*100)/100,n)});$('collectpure').onclick=collectPure;$('refresh').onclick=spotPrice;try{let s=JSON.parse(localStorage.getItem(`hedge.${key}`));if(s)Object.entries(s).forEach(([k,v])=>$(k).value=v)}catch(_){}spotPrice();render();
